name: {{ cookiecutter.env_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn
  - pandas
  - pre-commit
  - pytest
  - ipykernel
  # - click
  # - Sphinx
  - coverage
  - pip
  - pip:
    - -e .